const works = [
  {
    id: 1,
    title_zh: "小黑板",
    title_en: "The small chalkboard",
    name: "王佳恩",
    seat: "01",
    img: "image/works/01.jpg",
    ref: "image/drafts/01.jpg",
    desc_zh: "墨綠色的小黑板一直都靜靜的待在教室的一角，陪我們歡笑、陪我們哭、陪我們度過高中三年的時光。紀錄了功課、紀錄了考試，也紀錄了我們這三年來的心酸血淚史。對我而言，它就是我們高中三年的體現。",
    desc_en: "The dark green chalkboard has remained quietly in a corner of the classroom, accompanying us through our laughter,  tears, and  the entirety of our three-year high school journey.It kept track of our homework, our exams, and all the struggles we went through.To me, it is the embodiment of our three years of high school."
  },
  {
    id: 2,
    title_zh: "空殼學姐",
    title_en: "The hollow senior",
    name: "安祐萱",
    seat: "02",
    img: "image/works/02.jpg",
    ref: "image/drafts/02.jpg",
    desc_zh: "高二時生物老師帶了一個全身的骨骼放在班上，同學們發揮創意用各種道具裝飾，並稱呼為學姐。像是總拼命唸書的我們，會不會只剩下空殼呢？",
    desc_en: "When I was in my second year of high school, our biology teacher brought a full-body skeleton into the classroom. My classmates used all kinds of props to decorate it and called it “senior.” Like us, who are always desperately studying, could it be that we are left with nothing but empty shells?"
  },
  {
    id: 3,
    title_zh: "迎新餘角",
    title_en: "Side Glances of the Orientation",
    name: "朱韋蓁",
    seat: "03",
    img: "image/works/03.jpg",
    ref: "image/drafts/03.jpg",
    desc_zh: "歡騰的迎新相聚之間，以學妹迎新當日的合影為藍本，透過針尖的層疊塑形，不僅還原了照片中鮮活的笑靨與默契，更將那段為了共同目標而努力的純粹同窗情誼，封存於柔軟的觸感之中。作品意不在寫實，而在於捕捉那份專屬於高中歲月的熱忱與友誼溫度。",
    desc_en: "Captured during the lively junior orientation, this needle-felted piece is inspired by a group photo from that day. Through the delicate layering of wool, it not only recreates the bright smiles and shared chemistry in the picture but also encapsulates the pure bonds of friendship formed while working toward a common goal. Rather than focusing on realism, this work aims to preserve the warmth and passion unique to our high school years within its soft texture."
  },
  {
    id: 4,
    title_zh: "尖叫的卡拉OK",
    title_en: "Screaming Karaoke",
    name: "吳亦琁",
    seat: "04",
    img: "image/works/04.jpg",
    ref: "image/drafts/04.jpg",
    desc_zh: "高二那年的園遊會，我們班擺了一個結合卡拉OK、算命和套圈圈的攤位。其中套圈圈的獎品中有一隻尖叫雞的造型氣球，因為實在太可愛了，所以我就拿它在黑板前拍了這張照片。他對我來說不僅僅是個有趣的瞬間，同時也代表了我高中三年的歡樂回憶。",
    desc_en: "During the school fair in my second year of high school, our class set up a booth that combined karaoke, fortune-telling, and a ring toss game. One of the prizes for the ring toss was a screaming chicken balloon. Because it was so cute, I took a photo of it in front of the classroom blackboard. To me, this photo is not just a fun moment, but also a small symbol that captures my three years of high school memories."
  },
  {
    id: 5,
    title_zh: "綠・拾光",
    title_en: "Dream in Green",
    name: "吳星恬",
    seat: "05",
    img: "image/works/05.jpg",
    ref: "image/drafts/05.jpg",
    desc_zh: "紅磚道的巧克力雞，在陽光斜斜灑落的路口張開雙臂，從萬木春生，到夏木蔭翳，從秋葉喧囂，到冬日凄清。青春的動畫，定格在彰女暖暖朝陽裡。",
    desc_en: "On the red-brick path, a chocolate-colored chicken spreads its wings under slanting sunlight. From spring’s fresh leaves to summer’s shaded trees, from autumn’s bustling foliage to winter’s quiet chill, youth plays like an animation, frozen in the warm morning glow of Chang-Nu’s school."
  },
  {
    id: 6,
    title_zh: "國文課吐西瓜籽",
    title_en: "Spitting Watermelon Seeds in Chinese Class",
    name: "吳家溱",
    seat: "06",
    img: "image/works/06.jpg",
    ref: "image/drafts/06.jpg",
    desc_zh: "每年夏日將際之時，國文老師小P總會送我們班一顆國文科辦公室團購的西瓜。長長的西瓜刀被傳來傳去，陳年的木柄覆上青春的美好記憶。紅紅的西瓜分切後放在餘卷上，我努力弓起手掌，不想讓片刻的清涼從指間流走。那天單純的快樂，在回首之時變得更為珍貴。",
    desc_en: "Every year as summer approached, our Chinese teacher, Little P, would give our class a watermelon from the Chinese office group purchase. The long watermelon knife passed from hand to hand, its aged wooden handle coated in the golden memories of youth. Slices of red watermelon rested atop our textpapers; I cupped my hands tightly, desperate to keep that fleeting coolness from slipping through my fingers. That simple joy has  grown more precious with time."
  },
  {
    id: 7,
    title_zh: "那年盛夏的社聯",
    title_en: "euphoria",
    name: "吳湘翎",
    seat: "07",
    img: "image/works/07.jpg",
    ref: "image/drafts/07.jpg",
    desc_zh: "高二那年，為了踏出自己的舒適圈，我開始學習電繪並參與社展的設計。作品圖案取自我為社展創作的最後一張海報，我將它轉化為羊毛氈，希望以另一種形式保存這段關於成長、努力與青春的珍貴記憶。",
    desc_en: "In my 11th grade, I stepped out of my comfort zone by learning digital illustration and taking part in the design work for the club exhibition. The design of this piece comes from the last poster I created for the event.By recreating it in felted wool, I hope to preserve this precious memory of growth, effort, and youth in a different form."
  },
  {
    id: 8,
    title_zh: "停留的片刻",
    title_en: "A Moment of Pause",
    name: "李安禹",
    seat: "08",
    img: "image/works/08.jpg",
    ref: "image/drafts/08.jpg",
    desc_zh: "鳥的停留，不只是短暫的休息，也隱喻學生在學習中的思考與沉澱。在忙碌的校園生活中，每個人都需要屬於自己的節奏與空間。成長不只需要前進，也需要停留與觀察。",
    desc_en: "The bird’s pause is not merely a moment of rest; it also symbolizes students’ reflection and internalization in the process of learning. In the busy life of campus, everyone needs their own rhythm and personal space. Growth requires not only moving forward, but also pausing and observing."
  },
  {
    id: 9,
    title_zh: "那裡有五隻貓",
    title_en: "There are five cats there.",
    name: "林彤諺",
    seat: "09",
    img: "image/works/09.jpg",
    ref: "image/drafts/09.jpg",
    desc_zh: "這張照片是在拍畢業照那天和朋友一起拍的。照片中是一隻貓。我選擇這張照片是因為它看起來很可愛，而且也比較容易重現。此外，這張照片也代表了我的高中生活。裡面有我的朋友、操場和陽光，這些元素都讓我想起在學校的日子。我希望未來當我再次看到這個作品時，能夠想起這些回憶",
    desc_en: "This photo was taken on the day we took our graduation photos with my friends.The picture shows a cat. I chose this photo because it looks cute and is easier to recreate.Also, this photo represents my high school life. It includes my friends, the playground, and the sunshine. These elements remind me of my school days.I hope that in the future, when I see this artwork, I will think of these memories again."
  },
 {
    id: 10,
    title_zh: "立正～",
    title_en: "Attention",
    name: "林采螢",
    seat: "10",
    img: "image/works/10.jpg",
    ref: "image/drafts/10.jpg",
    desc_zh: "回顧過往那些當司儀的生活，不管是什麼典禮，學姐總會要求我們要立正站好，雖然常常腰痠背痛，不過仔細想想，那段時光其實也有蠻多有趣回憶的。",
    desc_en: "Looking back on those days when I worked as a MC, no matter what kind of ceremony it was, our senior always required us to stand up straight. Although it often left me with a sore back and waist, thinking about it now, that period of time actually holds quite a lot of interesting and memorable moments :)"
  },
 {
    id: 11,
    title_zh: "交會之境",
    title_en: "Crossroads Within",
    name: "林俞君",
    seat: "11",
    img: "image/works/11.jpg",
    ref: "image/drafts/11.jpg",
    desc_zh: "作品以校園小橋與周圍植物為靈感，透過羊毛氈呈現道路交會的意象，象徵高中階段面臨的選擇與轉折。圓形構圖與延伸線條營造出流動與層次，表達在成長過程中停下思考、尋找方向的心境。",
    desc_en: "Inspired by a small bridge and surrounding plants on campus, this wool felt piece depicts intersecting paths as a symbol of the choices and turning points during my high school years. The circular composition and extending lines create a sense of movement and depth, reflecting a moment of pause and self-reflection while searching for direction."
  },
 {
    id: 12,
    title_zh: "此時此刻",
    title_en: "Here and now",
    name: "柯承瑩",
    seat: "12",
    img: "image/works/12.jpg",
    ref: "image/drafts/12.jpg",
    desc_zh: "這件作品以我拍攝的照片為靈感，記錄了高一與高三待過的教學大樓。鐘樓上刻著「把握當下」，是我對自己的深切期許。作品中那些帶有彩色斑點的羊毛，一開始我並不喜歡，但轉念一想，這正如同我在彰女的高中生活：許多起初令我畏懼的挑戰，最後都化作生命中不可或缺的底色。唯有轉變心境、勇敢面對困難，才能交織出閃亮的高中回憶。",
    desc_en: "Inspired by photos I took, this piece captures the school buildings where I spent my first and final years. The words 'Seize the Day' on the clock tower represent my personal motto. I initially disliked the multicolored wool used here, but I soon realized it perfectly mirrors my life at school: many challenges that once intimidated me eventually became the vibrant colors of my journey. By shifting my perspective and facing difficulties head-on, I have woven together a truly brilliant high school life.irror the building's texture—a choice that initially felt strange but eventually came to represent my colorful and diverse life at CHGSH. By embracing challenges with a positive mindset, I’ve woven my growth into this piece."
  },
 {
    id: 13,
    title_zh: "綻放中的鳳凰",
    title_en: "Phoenix in bloom",
    name: "洪品熏",
    seat: "13",
    img: "image/works/13.jpg",
    ref: "image/drafts/13.jpg",
    desc_zh: "這顆座落於行政大樓下的櫻花樹，每年綻放時，都見證了我們在彰女一年又一年的蛻變，如今，他依然綻放著，而我們也已從高一新鮮人，準備乘著巧克力雞的羽翼向外翱翔。",
    desc_en: "This cherry blossom tree, located beneath the administrative building, blooms every year and witnesses our growth and transformation throughout our time at Changhua Girls’ Senior High School. Now, it is still blooming, while we have grown from freshmen into students ready to spread our wings and soar outward on the wings of the Chocolate Chicken."
  },
 {
    id: 14,
    title_zh: "風的牧場",
    title_en: "Windy Pasture",
    name: "籃妤喬",
    seat: "14",
    img: "image/works/14.jpg",
    ref: "image/drafts/14.jpg",
    desc_zh: "彰女三年，自由又隨性，卻又不經意的開拓人的視野，就像這個畫面一樣奔放自在。地上的羊、地上的花，一個象徵自由，一個象徵成長。而用羊毛交織的色彩展現出隨風搖曳的感覺，象徵出無拘束放鬆的生活。",
    desc_en: "During my three years at Changhua Girls’ Senior High School, life has been free and spontaneous, yet it has quietly broadened my perspective. Just like the scene in this artwork, it feels open and unrestrained.The sheep on the grass symbolize freedom, while the flowers represent growth. The interwoven colors of wool create a sense of grass swaying in the wind, expressing a carefree and relaxed way of life."
  },
 {
    id: 15,
    title_zh: "尋找小羊",
    title_en: "Looking for the sheep",
    name: "胡芯慈",
    seat: "15",
    img: "image/works/15.jpg",
    ref: "image/drafts/15.jpg",
    desc_zh: "這兩隻羊是彰女的某一個小角落的娃娃，非常可愛，但我一直找不到要去哪裡買同款的娃娃，如果有人有找到，或是有同款，我非常樂意收購。",
    desc_en: "These two sheep dolls are from a small corner of our school. They are very cute, but I have never been able to find where to buy the same ones. If anyone has found where to buy them, or has the same dolls, I would be very happy to buy them."
  },
 {
    id: 16,
    title_zh: "樹",
    title_en: "Tree",
    name: "凃潔安",
    seat: "16",
    img: "image/works/16.jpg",
    ref: "image/drafts/16.jpg",
    desc_zh: "白雲和藍天，冬天時還會開著山櫻花，這裡絕對是彰女最美的祕境。設計作品時，我希望能表現出樹冠茂密、像絨毛一樣柔軟的感覺，因此不把羊毛戳得太緊實，刻意保留一些蓬鬆感，讓它看起來像一叢一叢自然生長的樣子。",
    desc_en: "Under the azure sky and white clouds, winter brings the blooming of mountain cherries—a scene that marks the most stunning secluded corner of CHGSH. In my design, I aimed to evoke the soft, velvety texture of a dense canopy. By purposely keeping the wool loose and airy rather than firm, I allowed the piece to retain a delicate fluffiness, mimicking the organic, layered clusters found in nature."
  },
 {
    id: 17,
    title_zh: "寧靜的早晨",
    title_en: "A Peaceful Morning",
    name: "高偲晴",
    seat: "17",
    img: "image/works/17.jpg",
    ref: "image/drafts/17.jpg",
    desc_zh: "作品呈現綠蔭環繞的校園步道，中央為學校象徵性的鳳凰裝置藝術。筆直的小徑引導視線向前，象徵學生在校園中不斷前行、學習與成長，朝向充滿希望與未來的方向。",
    desc_en: "This artwork shows a tree-lined campus pathway with the school’s symbolic Phoenix installation at its center. The straight path leads the viewer’s gaze forward, representing students moving ahead, learning and growing toward a hopeful future."
  },
 {
    id: 18,
    title_zh: "樹樹樹",
    title_en: "Tree",
    name: "張畇蓁",
    seat: "18",
    img: "image/works/18.jpg",
    ref: "image/drafts/18.jpg",
    desc_zh: "這張粉紅風鈴木的照片是我在一年級春天拍的，我覺得很像是一幅生動的畫作。那時的空氣彌漫著清新的氣息，陽光灑在大地上，沒有很熱，甚至還有微風，是我最喜歡的瞬間。而它盛開的粉紅色花朵迎接新學期的到來，像是在期許彰女學生們能夠有美好的開始。",
    desc_en: "This photo of the Rosy Trumpet Tree was taken by me in the spring of my first year at school. I think it looks like a vivid painting. At that time, the air was filled with a fresh scent, and sunlight spread across the ground. It wasn’t very hot, and there was even a gentle breeze. This was my favorite kind of moment. The blooming pink flowers welcomed the arrival of the new semester, as if wishing the students of CHGSH a wonderful beginning."
  },
 {
    id: 19,
    title_zh: "發呆小黑",
    title_en: "Space out",
    name: "許芮瑛",
    seat: "19",
    img: "image/works/19.jpg",
    ref: "image/drafts/19.jpg",
    desc_zh: "在校園裡，黑冠麻鷺常常安靜地出現在草地或樹下，慢慢走動、停下來發呆或觀察四周。牠們看起來不太在意人群，像是習慣了學生的來來去去。",
    desc_en: "In many campuses, the Malayan night heron can often be seen quietly standing on lawns or beneath trees, slowly walking and occasionally stopping to stare into space or observe its surroundings. It seems unfazed by people, as if it has grown used to the constant flow of students passing by."
  },
 {
    id: 20,
    title_zh: "課後餘暉",
    title_en: "Twilight over the campus",
    name: "許淳涵",
    seat: "20",
    img: "image/works/20.jpg",
    ref: "image/drafts/20.jpg",
    desc_zh: "紫紅晚霞交織，映照著規整的窗櫺與校園綠意，記錄下放學後溫柔而寧靜的課後餘暉，而我將那抹轉瞬即逝的晚霞永久珍藏。",
    desc_en: "Purple and rosy clouds blend together, mirroring the orderly windows and lush greenery. This piece records the tender, quiet evening glow after class, preserving the fleeting beauty of the twilight forever."
  },
 {
    id: 21,
    title_zh: "雲下的我們",
    title_en: "Changing Sky With Unchanged Mind",
    name: "郭芷菱",
    seat: "21",
    img: "image/works/21.jpg",
    ref: "image/drafts/21.jpg",
    desc_zh: "天空變幻無常，像高中生活一般，而這顆由雲交織而成的「心」，亦並非真正恆久存在，卻象徵著內心深處那份不易動搖的情感與初心。即使外在世界不斷改變，如同天空般無法掌控，仍希望我們心中那顆擁抱夢想的心永恆不變。",
    desc_en: "The sky shifts endlessly, much like the journey of high school, ever in motion.And this heart, woven gently from drifting clouds, is never meant to last,yet it reflects the quiet strength within us—our emotions and our beginnings, held fast.Even as the world keeps changing, vast and beyond our control, like the restless sky above, we still hope the heart within us—the one that dares to dream—remains unchanged, steady as ever."
  },
 {
    id: 22,
    title_zh: "春天的足跡",
    title_en: "The Footprints of Spring",
    name: "郭祐竹",
    seat: "22",
    img: "image/works/22.jpg",
    ref: "image/drafts/22.jpg",
    desc_zh: "每年三月初的早晨，穿越彰女門口的刷卡機，都能看見粉紅風鈴木盛開的景象，微風吹過，花瓣便如雨滴般落下，在我們心中留下獨一無二回憶。",
    desc_en: "On the mornings of early March each year, passing through the card reader at the entrance of Zhangnu Gate, you can see the scene of pink tabebuia trees in full bloom. When the breeze blows, the petals fall like raindrops, leaving a unique memory in our hearts."
  },
 {
    id: 23,
    title_zh: "友",
    title_en: "Friendship",
    name: "陳俞安",
    seat: "23",
    img: "image/works/23.jpg",
    ref: "image/drafts/23.jpg",
    desc_zh: "不同班、甚至不同屆的我們，因為有了共同的目標而聚在一起，我們一起面對實驗中的高潮與低谷，共同經歷比賽時的緊張與焦慮，那些存在於回憶中的苦與甘、笑與淚，都是這段青春最好的見證。",
    desc_en: "Students from different classes—even different grades—came together because we shared a common goal. We faced the highs and lows of experiments side by side, and experienced the tension and anxiety of competitions together. The bitterness and sweetness, the laughter and tears preserved in our memories, all stand as the best testament to this chapter of our youth."
  },
 {
    id: 24,
    title_zh: "回望之間",
    title_en: "Between a Glance",
    name: "鐘以心",
    seat: "24",
    img: "image/works/24.jpg",
    ref: "image/drafts/24.jpg",
    desc_zh: "紅磚鋪展的校園裡，一隻名為「巧克力雞」的鳥靜靜佇立，與一位女孩的背影對望。月光穿過枝葉灑落，時間在目光交會的瞬間緩緩流動。從初春的嫩綠，到盛夏的濃蔭，從秋日的微涼，到冬季的寧靜，四季在無聲中更迭。青春，彷彿停留在那一刻——在彰女熟悉而溫暖的校園裡，被悄悄收藏。",
    desc_en: "On the red-brick campus, a bird named “Chocolate Chicken” stands quietly, gazing toward the back of a girl. Sunlight filters through the leaves, and time flows gently within that silent exchange of glances. From the tender green of spring to the dense shade of summer, from the cool air of autumn to the calm of winter, the seasons pass in quiet succession.Youth seems to pause in that very moment—softly preserved within the familiar and warm campus of Chang-Nu."
  },
 {
    id: 25,
    title_zh: "盼",
    title_en: "Celeste",
    name: "謝靖淇",
    seat: "25",
    img: "image/works/25.jpg",
    ref: "image/drafts/25.jpg",
    desc_zh: "碧色偃喧囂，誰與憑欄倚────致一段不那麼恣意燦爛的青春。盼有兩個意義，既是憑欄而盼，也是心中所冀望。無比燦亮的藍天與綠樹之景，象徵著光明的未來，這也正是我們每個人最深的盼望。同時也感謝陪在身旁，一同逐夢的夥伴們，因為有你們，我才有繼續前進的動力。",
    desc_en: "Whenever your heart feels heavy, lift your eyes to the boundless sky."
  },
 {
    id: 26,
    title_zh: "暫時的寧靜",
    title_en: "Maze of Memories",
    name: "黃采薇",
    seat: "26",
    img: "image/works/26.jpg",
    ref: "image/drafts/26.jpg",
    desc_zh: "彰女紅樓是極具歷史意義的建築遺跡，除此以外它也充斥在我高二生活的每一天當中，因為每每望向窗外便能看見它的身影。這張照片是在一個春天的早晨拍的，陽光灑下來的瞬間彷彿讓時間凝滯，帶著所有人進入屬於這棟紅樓的記憶迷宮。",
    desc_en: "The Red Building is a historical architectural site. It also fills every day of my life in senior high school second grade because I can see it every time I look out of the window. This photo was taken on a spring morning, the moment when the sunshine falls down seems to make time stagnate, bringing everyone back to the memory maze that belongs to this Red Building."
  },
 {
    id: 27,
    title_zh: "我是小黑",
    title_en: "I’m Xiaohei",
    name: "黃咨寧",
    seat: "27",
    img: "image/works/27.jpg",
    ref: "image/drafts/27.jpg",
    desc_zh: "小黑常在校園裡遊蕩，看到人有時會突然衝撞，有時又莫名其妙地亂叫，沒有人知道牠到底在做什麼。某種程度上，牠其實很像我的高中生活——每天看起來忙忙亂亂，也不知道在幹嘛，但就這樣一路走到了現在。",
    desc_en: "Xiaohei often wanders around campus. Sometimes he suddenly charges at people, and sometimes he just calls out for no obvious reason. No one really knows what he’s doing. In a way, he reminds me of my high school life—busy, a little chaotic, and often confusing, but somehow it still brought me all the way here."
  },
 {
    id: 28,
    title_zh: "難求、籃球",
    title_en: "Precious memories with basketball",
    name: "黃宥潔",
    seat: "28",
    img: "image/works/28.jpg",
    ref: "image/drafts/28.jpg",
    desc_zh: "下午的體育課，陽光斜斜地灑在操場上，微風輕輕吹過，帶走一天的悶熱。我和同學一起在球場上奔跑、傳球、笑鬧，汗水在陽光下閃著光。那一刻沒有考試的壓力，也沒有未來的煩惱，只有單純的快樂與青春的活力。或許多年以後回想起來，這樣普通卻溫暖的時光，才是學生時代最可貴、最令人懷念的片段。",
    desc_en: "During the afternoon PE class, sunlight gently spreads across the playground while a soft breeze drifts through the air. My classmates and I run across the court, passing the ball, laughing, and enjoying the moment together. Sweat glimmers under the sunlight, and for a while there is no pressure from exams and no worries about the future. There is only simple happiness and the vibrant energy of youth. Perhaps years later, when we look back, we will realize that these ordinary yet warm moments—playing sports with friends under the sun and breeze—were truly some of the most precious memories of our school days."
  },
 {
    id: 29,
    title_zh: "二年級教室外紅磚道",
    title_en: "The red brick road outside of the second grade building",
    name: "劉晏芮",
    seat: "29",
    img: "image/works/29.jpg",
    ref: "image/drafts/29.jpg",
    desc_zh: "在整個高中的記憶裡，屬於這條紅磚道的記憶儼然發光，我們在這裡遛烏龜，生物課困頓時在這裡拔草，下課在這裡找幸運草。這是一條承載了我們高中生活的，回憶的紅磚道。",
    desc_en: "In all my memories of high school, those belonging to this red brick path seem to glow. We walked turtles here, pulled weeds here when we felt drowsy in biology class, and searched for lucky clovers here during breaks. This is a red brick path that carries our high school life and our memories."
  },
 {
    id: 30,
    title_zh: "拾月之溫",
    title_en: "Catching Moonbeams",
    name: "劉瑩茜",
    seat: "30",
    img: "image/works/30.jpg",
    ref: "image/drafts/30.jpg",
    desc_zh: "這件作品以成果發表海報為主題，將高中三年深刻的青春烙印，化作指尖揉捏與戳刺的觸感。透過質樸的羊毛纖維疊加光影，嘗試捕捉海報中那抹靜謐月色下的夢想與熱血。它不只是一個物件，更是對那段純粹時光的溫柔定格，在柔軟的質地中，包裹著一顆追逐星芒、無懼未來的少年心。",
    desc_en: "Inspired by the graduation exhibition poster, this piece transforms three years of indelible high school memories into a tactile art form. Through the layering of wool fibers, I captured the dreams and passion beneath the serene moonlight. It is more than a craft; it is a gentle freezing of time, encasing a youthful heart that once chased the starlight and now bravely faces the future within its soft texture."
  },
 {
    id: 31,
    title_zh: "過去、現在、未來",
    title_en: "Past, present,future",
    name: "蔡宜臻",
    seat: "31",
    img: "image/works/31.jpg",
    ref: "image/drafts/31.jpg",
    desc_zh: "畫面的右側象徵著高一的我，代表著已經走過的過去；左側則指向高三，代表著尚未抵達的未來。我所站立的位置象徵著當下，而在那之後，高二的歲月正悄然消逝——它並未正面呈現，而是在無意識中被留在身後。這種構圖安排，反映了青春歲月的轉瞬即逝，以及那些時光難以捉摸、難以留存的本質。",
    desc_en: "The right side of the composition symbolizes my 10th-grade self, representing a past already lived, while the left points toward 12th grade, representing a future yet to be reached. My current position signifies the present, behind which my 11th-grade year is quietly slipping away—not depicted head-on, but unconsciously left in my wake. This arrangement reflects the rapid flight of youth and the fleeting, elusive nature of these moments."
  },
 {
    id: 32,
    title_zh: "飛起來的瞬間",
    title_en: "The moment of leap",
    name: "謝宜蓁",
    seat: "32",
    img: "image/works/32.jpg",
    ref: "image/drafts/32.jpg",
    desc_zh: "高二的生活，既沒有高一的懵懂，亦沒有高三的升學壓力。擔任社幹的生活相當充實，閒暇之餘則會和同儕一起打球，飛躍的瞬間，不僅揮灑汗水，更享受著僅此一次的青春。",
    desc_en: "The second year of high school is neither as naive as freshman year nor as pressured by college entrance exams as senior year. Life as a club teacher  assistant is fulfilling and busy, while in my free time, I play volleyball with my friends. In those moments of leaping into the air, I’m not only sweating it out, but also enjoying this once-in-a-lifetime youth."
  }
];

